server:
  port: 8888     #http://localhost:8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Asd8711341
    url: jdbc:mysql://101.200.216.156:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  cloud:
    zookeeper:
      connect-string: localhost:2181
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc.springcloud81.misprovider.dao: debug    #  None, fatal,error,warning,info,debug,all
